config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 10, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  validates :user_id, presence: true

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true,
    uniqueness: { case_sensitive: false },
    length: {minimum: 3, maximum: 25}

  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { minimum: 5, maximum: 25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
    uniqueness: { case_sensitive: false},
    length: { maximum: 105},
    format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action."
      redirect_to root_path
    end
  end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def new
  	@article = Article.new
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @article = set_article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article has been successfully created."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

def update
  @article = set_article
  if @article.update(article_params)
    flash[:success] = "Article was successfully updated"
    redirect_to article_path(@article)
  else
    render 'edit'
  end
end

  def show
    @article = set_article
  end

  def destroy
    @article = set_article
    @article.destroy
    flash[:danger] = "Article was deleted"
    redirect_to articles_path
  end

  
  private

    def set_article
      @article = Article.find(params[:id])

    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You may only manage your own articles"
        redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

   before_action :require_admin, except: [:index, :show]

  def index
  	@categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
  	@category = Category.new
  end

 
  def create
  	@category = Category.new(category_params)
	  if @category.save
	  	flash[:success] = "Category was created successfully"
	  	redirect_to categories_path

	  else
	  	render 'new'
	  end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was sucessfully updated."
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end  
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end

def create
	user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "You have successfully logged in."
    redirect_to user_path(user)
  else
    flash.now[:danger] = "There was something wrong with log in information."
    render 'new'
  end		
end

def destroy
	session[:user_id] = nil
	flash[:success] = "You have successfully logged out."
	redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the NateBlog #{@user.username}"
  	  redirect_to user_path(@user)
  	else
  		render 'new'
  	end
  end

  def edit
  
  end

  def update
    if @user.update(user_params)
    	flash[:success] = "Your Account was updated successfully."
      redirect_to articles_path
    else render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all associated articles have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
     @user = User.find(params[:id])
  end
 
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end 

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perfrom that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "img-cirlce")
  end


end

app/views/articles/_article.html.erb
  <% obj.each do |article| %>
    <div class="row">
      <div class="col-sm-8 offset-sm-2">
        <div class="card card-lg bg-light">
          <div class="article-title">  
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
    	      <%= truncate(article.description, length: 100) %>
            <div class="article-meta-details">
            <small>Created By: <%= article.user.username %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %></small>
            </div>
          </div>
              <div class="article-actions">
                <% if article.categories.any? %>
                  <p>Categories: <%= render article.categories %></p>
                <% end %>
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-sm btn-primary" %>
                <%= link_to "Destroy this article", article_path(article),
                  method: :delete,
                  data: { confirm: "Has this article been chosen?"}, 
                  class: "btn btn-sm btn-danger" %>
                <% end %>
              </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="container">
	<div class='row'>
		<div class="col-sm-12">
			<%= form_for(@article, :html => {class: "form", role: "form"}) do |f| %>
			  <div class="form-group row">
				  <div class="col-sm-2 col-form-label text-right">
			      <%= f.label :title %>
			    </div>
		      <div class="col-sm-8">
		        <%= f.text_area :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
			    </div>
			  </div>
				<div class="form-group row">
				  <div class="col-form-label col-sm-2 text-right">
				    <%= f.label :description %>
				  </div>
			    <div class="col-sm-8">
				    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article", autofocus: true %>
				  </div>
				</div>
				<div class="form-group row justify-content-center">
		  		<div class="col-sm-8 center ">
			      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
			      <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
 			      <% end %>
			    </div>
			  </div>
		  	<div class="form-group row justify-content-center">
		  		<div class="col-sm-8">
			      <%= f.submit class: "btn-dark btn-lg btn-block" %>
			    </div>
			  </div>
			<% end %>
	  <div class="row">
	    <div class="col-sm-6 offset-sm-4">
	    	[ <%= link_to "Cancel Request and Return to Article Listing", articles_path %> ]
	    </div>
	  </div>
	</div>


<div class="BackToArticle">
  <%= link_to "Back to Article Index", articles_path %>
</div>

app/views/articles/edit.html.erb
<h1 align = "center">Edit Existing Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">Articles Index</h1>

<%= will_paginate %>
<%= render 'article', obj: @articles %>
<%= will_paginate %>

app/views/articles/new.html.erb
<h1 align="center">New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><strong>Title: <%= @article.title %></strong></h2>
<div class="card bg-light col-sm-8 offset-sm-2">
  <div class="article-list center">
    <li>Created by:</li> 
    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
    <li><%= link_to @article.user.username, user_path(@article.user) %></li>       
    <small>
      <li><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></li>
      </small>
    </div>
	<h4 class="center description"><strong>Description:</strong></h4>
	<div class="description-body">
    <%=simple_format(@article.description) %>
    <div>
      <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
      <% end %>
    </div>
  </div>
  <div class="article-actions">
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-sm btn-primary" %>
        <%= link_to "Destroy this article", article_path(@article),
          method: :delete,
          data: { confirm: "Has this article been chosen?"}, 
          class: "btn btn-sm btn-danger" %>
      <% end %>
  </div>

</div>

app/views/categories/_category.html.erb
<span class="badge"><%=  link_to category.name, category_path(category) %> &nbsp;

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<div class="container">
			<%= form_for(@category, :html => {class: "form", role: "form"}) do |f| %>
			  <div class="form-group row">
				  <div class="col-sm-2 col-form-label text-right">
			      <%= f.label :category %>
			    </div>
		      <div class="col-sm-8">
		        <%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
			    </div>
			  </div>
		  	<div class="form-group row justify-content-center">
		  		<div class="col-sm-8">
			      <%= f.submit class: "btn-dark btn-lg btn-block" %>
			    </div>
			  </div>
			  </div>
			<% end %>
	  <div class="row">
	    <div class="col-sm-6 offset-sm-4">
	    	[ <%= link_to "Cancel Request and Return to Article Listing", articles_path %> ]
	    </div>
	  </div>
	</div>


<div class="BackToArticle">
  <%= link_to "Back to Article Index", articles_path %>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>


<%= will_paginate %>
	<% @categories.each do |category| %>
		<ul class="listing">
			<div class="row justify-content-center">
				<div class="card-category card-lg bg-light col-sm-6">
					<li class="article-title">
						<%= link_to "#{category.name}",  category_path(category) %>
						<li style="list-style: none;"><small><%= pluralize(category.articles.count, "article") %></small></li>
					</li>
				</div>
			</div>
		</ul>
	<% end %>
<%= will_paginate %>

app/views/categories/new.html.erb
<h1 align="center">Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
  <% if logged_in? and current_user.admin? %>
	<span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
	<% end %>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; Nate B
    </small>
    <nav>
      <ul>
      	<li><%= link_to "About", about_path %></li>
      </ul>   
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class=" col-sm-10 offset-sm-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %>'>
  	  <a href="#" class="close" data-dismiss="alert">&#215;</a>
  	  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Nate Blog", root_path, class: "navbar-brand", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "New Article", new_article_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <ul class="dropdown-item" style="list-style: none;">
            <li><%= link_to "All Categories", categories_path(current_user) %></li>
          </ul>
            <div class="dropdown-divider"></div>  
            <ul style="list-style: none; padding: 0px;">
            <% Category.all.each do |category| %>
              <li class="dropdown-item" style="padding-top: 0px; padding-bottom: 0px;"><%= link_to "#{category.name}", category_path(category) %></li> 
            <% end %>
          </ul>
          <% if logged_in? and current_user.admin? %>
            <div class="dropdown-divider"></div>
            <ul class="dropdown-item" style="list-style: none;">
              <li><%= link_to "Create New Category", new_category_path %></li>
            </ul>
          <% end %> 
        </div>
      </li>
      
 <!--      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Profile <%= "Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarDropdown">
            <a class="dropdown-item"><%= link_to "Edit your profile", edit_user_path(current_user) %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item"><%= link_to "View your profile", user_path(current_user) %></a>
          </div>
        </li>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NateBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container center">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<%= link_to "home", root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>NateBlog</h1>
  <% if !logged_in? %>
    <%= link_to "Sign Up Now", signup_path, class: "btn btn-dark btn-lg" %>
   <% end %>
  <p>
    <%= link_to "THE BLOG", articles_path %> | <%= link_to "ABOUT", about_path %>
  </p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
  	<div class="col-sm-8 offset-sm-2">
  		<div class="alert alert-danger">
  			<div class="alert-heading">
  				<h2 class="alert-title">
  					<%= pluralize(obj.errors.count, "error") %>
					prevented article from being saved:</h2>
					<div class="alert-body">
						<ul>
						  <% obj.errors.full_messages.each do |msg| %>
						    <li><%= msg %></li>
						  <% end %>
						</ul>
					<% end %>
				</div>
		  </div>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="container">
	<div class='row'>
		<div class="col-sm-12">
			<%= form_for(@user, :html => {class: "form", role: "form"}) do |f| %>
			  <div class="form-group row">
				  <div class="col-sm-2 col-form-label text-right">
			      <%= f.label :username %>
			    </div>
		      <div class="col-sm-8">
		        <%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
			    </div>
			  </div>
				<div class="form-group row">
				  <div class="col-form-label col-sm-2 text-right">
				    <%= f.label :email %>
				  </div>
			    <div class="col-sm-8">
				    <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", autofocus: true %>
				  </div>
				</div>
				<div class="form-group row">
				  <div class="col-form-label col-sm-2 text-right">
				    <%= f.label :password %>
				  </div>
			    <div class="col-sm-8">
				    <%= f.password_field :password,  class: "form-control", placeholder: "password", autofocus: true %>
				  </div>
				</div>
		  	<div class="form-group row justify-content-center">
		  		<div class="col-sm-8">
			      <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn-dark btn-lg btn-block") %>
			    </div>
			  </div>
			  </div>
			<% end %>
	  <div class="row">
	    <div class="col-sm-6 offset-sm-4">
	    	[ <%= link_to "Cancel Request and Return to Article Listing", articles_path %> ]
	    </div>
	  </div>
	</div>


<div class="BackToArticle">
  <%= link_to "Back to Article Index", articles_path %>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">NateBlog Users</h1>

<div align="center">
  <%= will_paginate %> 
  <% @users.each do |user| %>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="card card-lg bg-light">
        <div class="article-list">  
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li><%= link_to user.username, user_path(user) %></li>       
          <small>
            <li><%= pluralize(user.articles.count, "article") if user.articles %></li>
            <li>User created:<%= time_ago_in_words(user.created_at) %> ago</li>
            <li>User last updated: <%= time_ago_in_words(user.updated_at) %></li>
          </small>
          <% if logged_in? and current_user.admin? %>
          <%= link_to "Edit User", edit_user_path(user), class: "btn btn-sm btn-primary" %>
          <%= link_to "Destroy this User", user_path(user),
            method: :delete,
            data: { confirm: "Has this user been chosen?"}, 
            class: "btn btn-sm btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>  
<% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">SignUp for the NateBlog </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
	<div class="col-sm-4 offset-sm-4 center">
		<%= gravatar_for @user %>
	</div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
	<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user.articles %>
<div class="center">
	<%= will_paginate @user_articles %>
</div>